language: node_js
notifications:
  email: false
node_js:
  - 'node'
  - 'lts/*'
sudo: false
cache:
  directories:
    - node_modules
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script:
- npm install tape-run
- npm run bootstrap
script:
- npm run test:ci
before_deploy:
- npm run jsdoc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: out
  target_branch: gh-pages
branches:
  only:
    - master
addons:
  apt:
    packages:
      - xvfb
  chrome: stable
  firefox: latest
