language: node_js
notifications:
  email: false
node_js:
  - 'lts/*'
  - 'node'
sudo: false
cache: npm
script:
  - npm run test
before_deploy:
- npm run jsdoc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: docs
  target_branch: gh-pages
branches:
  only:
    - master
