language: node_js
notifications:
  email: false
node_js:
  - 'node'
sudo: false
cache:
  directories:
    - node_modules
before_script:
- npm run bootstrap
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: out
  target_branch: gh-pages
branches:
  only:
    - master